<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Prosody/Prosody.csproj" />
    <Content
      Include="../../target/release/libprosody_ffi.dylib"
      Link="libprosody_ffi.dylib"
      CopyToOutputDirectory="PreserveNewest"
      Condition="Exists('../../target/release/libprosody_ffi.dylib')"
    />
    <Content
      Include="../../target/release/libprosody_ffi.so"
      Link="libprosody_ffi.so"
      CopyToOutputDirectory="PreserveNewest"
      Condition="Exists('../../target/release/libprosody_ffi.so')"
    />
    <Content
      Include="../../target/release/prosody_ffi.dll"
      Link="prosody_ffi.dll"
      CopyToOutputDirectory="PreserveNewest"
      Condition="Exists('../../target/release/prosody_ffi.dll')"
    />
  </ItemGroup>
</Project>
