using Prosody.Native;
using Xunit;

namespace Prosody.Tests.Unit;

/// <summary>
/// Unit tests for FFI type definitions generated by Interoptopus.
/// Verifies struct layouts, enum values, and marshalling compatibility.
/// </summary>
public class FFITypesTests
{
    // ==========================================================================
    // ConsumerState enum tests
    // ==========================================================================

    [Fact]
    public void ConsumerState_Unconfigured_HasExpectedValue()
    {
        var state = ConsumerState.Unconfigured;
        Assert.True(state.IsUnconfigured);
        Assert.False(state.IsConfigured);
        Assert.False(state.IsRunning);
    }

    [Fact]
    public void ConsumerState_Configured_HasExpectedValue()
    {
        var state = ConsumerState.Configured;
        Assert.False(state.IsUnconfigured);
        Assert.True(state.IsConfigured);
        Assert.False(state.IsRunning);
    }

    [Fact]
    public void ConsumerState_Running_HasExpectedValue()
    {
        var state = ConsumerState.Running;
        Assert.False(state.IsUnconfigured);
        Assert.False(state.IsConfigured);
        Assert.True(state.IsRunning);
    }

    [Fact]
    public void ConsumerState_ToString_ReturnsCorrectStrings()
    {
        Assert.Equal("Unconfigured", ConsumerState.Unconfigured.ToString());
        Assert.Equal("Configured", ConsumerState.Configured.ToString());
        Assert.Equal("Running", ConsumerState.Running.ToString());
    }

    // ==========================================================================
    // FFIErrorCode enum tests
    // ==========================================================================

    [Fact]
    public void FFIErrorCode_Ok_IsSuccess()
    {
        var code = FFIErrorCode.Ok;
        Assert.True(code.IsOk);
    }

    [Fact]
    public void FFIErrorCode_AllCodes_HaveDistinctValues()
    {
        // Verify all error codes are accessible and distinct
        var codes = new[]
        {
            FFIErrorCode.Ok,
            FFIErrorCode.NullPassed,
            FFIErrorCode.Panic,
            FFIErrorCode.InvalidArgument,
            FFIErrorCode.ConnectionFailed,
            FFIErrorCode.Cancelled,
            FFIErrorCode.Internal,
            FFIErrorCode.InvalidContext,
            FFIErrorCode.AlreadySubscribed,
            FFIErrorCode.NotSubscribed,
        };

        // Each should report its own type as true
        Assert.True(codes[0].IsOk);
        Assert.True(codes[1].IsNullPassed);
        Assert.True(codes[2].IsPanic);
        Assert.True(codes[3].IsInvalidArgument);
        Assert.True(codes[4].IsConnectionFailed);
        Assert.True(codes[5].IsCancelled);
        Assert.True(codes[6].IsInternal);
        Assert.True(codes[7].IsInvalidContext);
        Assert.True(codes[8].IsAlreadySubscribed);
        Assert.True(codes[9].IsNotSubscribed);
    }

    [Fact]
    public void FFIErrorCode_ToString_ReturnsCodeNames()
    {
        Assert.Equal("Ok", FFIErrorCode.Ok.ToString());
        Assert.Equal("NullPassed", FFIErrorCode.NullPassed.ToString());
        Assert.Equal("Panic", FFIErrorCode.Panic.ToString());
        Assert.Equal("InvalidArgument", FFIErrorCode.InvalidArgument.ToString());
        Assert.Equal("ConnectionFailed", FFIErrorCode.ConnectionFailed.ToString());
        Assert.Equal("Cancelled", FFIErrorCode.Cancelled.ToString());
        Assert.Equal("Internal", FFIErrorCode.Internal.ToString());
        Assert.Equal("InvalidContext", FFIErrorCode.InvalidContext.ToString());
        Assert.Equal("AlreadySubscribed", FFIErrorCode.AlreadySubscribed.ToString());
        Assert.Equal("NotSubscribed", FFIErrorCode.NotSubscribed.ToString());
    }

    // ==========================================================================
    // FFIClientOptions struct tests
    // ==========================================================================

    [Fact]
    public void FFIClientOptions_CanBeCreated()
    {
        // Verify the struct can be instantiated with default values
        var options = new FFIClientOptions();
        Assert.NotNull(options.ToString());
    }

    [Fact]
    public void FFIClientOptions_RequiredFieldsCanBeSet()
    {
        var options = new FFIClientOptions
        {
            bootstrap_servers = "localhost:9092",
            group_id = "test-group",
            subscribed_topics = "test-topic",
        };

        Assert.Equal("localhost:9092", options.bootstrap_servers);
        Assert.Equal("test-group", options.group_id);
        Assert.Equal("test-topic", options.subscribed_topics);
    }

    [Fact]
    public void FFIClientOptions_OptionalFields_MustBeExplicitlySet()
    {
        // IMPORTANT: Due to C# struct semantics, Option fields inside structs are
        // zero-initialized (not constructed) when the containing struct is default-initialized.
        // This means they appear as Some(default) instead of None.
        //
        // The correct pattern is to use ProsodyClientOptionsBuilder which explicitly
        // sets all Option fields to None, or explicitly assign each field.
        var options = new FFIClientOptions
        {
            // Explicitly set optional fields to None
            allowed_events = OptionConstPtrI8.None,
            source_system = OptionConstPtrI8.None,
            failure_topic = OptionConstPtrI8.None,
            cassandra_nodes = OptionConstPtrI8.None,
            max_concurrency = OptionU32.None,
            send_timeout_ms = OptionU64.None,
            max_retries = OptionU32.None,
            mock = OptionBool.None,
            monopolization_enabled = OptionBool.None,
            defer_enabled = OptionBool.None,
        };

        // Verify fields are now None
        Assert.True(options.allowed_events.IsNone);
        Assert.True(options.source_system.IsNone);
        Assert.True(options.failure_topic.IsNone);
        Assert.True(options.cassandra_nodes.IsNone);
        Assert.True(options.max_concurrency.IsNone);
        Assert.True(options.send_timeout_ms.IsNone);
        Assert.True(options.max_retries.IsNone);
        Assert.True(options.mock.IsNone);
        Assert.True(options.monopolization_enabled.IsNone);
        Assert.True(options.defer_enabled.IsNone);
    }

    // ==========================================================================
    // Option type tests
    // ==========================================================================

    [Fact]
    public void OptionU32_Some_HasValue()
    {
        var option = OptionU32.Some(42);
        Assert.True(option.IsSome);
        Assert.False(option.IsNone);
        Assert.Equal(42u, option.AsSome());
    }

    [Fact]
    public void OptionU32_None_HasNoValue()
    {
        var option = OptionU32.None;
        Assert.False(option.IsSome);
        Assert.True(option.IsNone);
    }

    [Fact]
    public void OptionU64_Some_HasValue()
    {
        var option = OptionU64.Some(1000);
        Assert.True(option.IsSome);
        Assert.Equal(1000ul, option.AsSome());
    }

    [Fact]
    public void OptionI32_Some_HandlesNegativeValues()
    {
        var option = OptionI32.Some(-1);
        Assert.True(option.IsSome);
        Assert.Equal(-1, option.AsSome());
    }

    [Fact]
    public void OptionBool_Some_True()
    {
        var option = OptionBool.Some(true);
        Assert.True(option.IsSome);
        Assert.True(option.AsSome());
    }

    [Fact]
    public void OptionBool_Some_False()
    {
        var option = OptionBool.Some(false);
        Assert.True(option.IsSome);
        Assert.False(option.AsSome());
    }

    [Fact]
    public void OptionConstPtrI8_Some_HasStringValue()
    {
        var option = OptionConstPtrI8.Some("test-value");
        Assert.True(option.IsSome);
        Assert.Equal("test-value", option.AsSome());
    }

    // ==========================================================================
    // Result type tests
    // ==========================================================================

    [Fact]
    public void ResultConstPtrProsodyClientServiceFFIErrorCode_Ok_IsSuccess()
    {
        var result = ResultConstPtrProsodyClientServiceFFIErrorCode.Ok(IntPtr.Zero);
        Assert.True(result.IsOk);
        Assert.False(result.IsErr);
        Assert.False(result.IsPanic);
        Assert.False(result.IsNull);
    }

    [Fact]
    public void ResultConstPtrProsodyClientServiceFFIErrorCode_Err_HasErrorCode()
    {
        var result = ResultConstPtrProsodyClientServiceFFIErrorCode.Err(FFIErrorCode.InvalidArgument);
        Assert.False(result.IsOk);
        Assert.True(result.IsErr);
        Assert.True(result.AsErr().IsInvalidArgument);
    }

    [Fact]
    public void ResultConstPtrProsodyClientServiceFFIErrorCode_ToString_ShowsStatus()
    {
        var okResult = ResultConstPtrProsodyClientServiceFFIErrorCode.Ok(IntPtr.Zero);
        var errResult = ResultConstPtrProsodyClientServiceFFIErrorCode.Err(FFIErrorCode.Internal);

        Assert.Equal("Ok(...)", okResult.ToString());
        Assert.Equal("Err(Internal)", errResult.ToString());
    }
}
